name: Deploy to UAT

on:
  push:
    branches:
      - develop

jobs:
  deploy-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate UAT Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > authfile.txt
          sf org login sfdx-url --sfdx-url-file authfile.txt --alias UAT

      - name: Deploy to UAT
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org UAT \
            --test-level RunSpecifiedTests \
            --tests PrintNumbersTest